---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: plasma
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
#base-image: ghcr.io/ublue-os/silverblue-main
#image-version: latest # You can pin to a specific version of Fedora as well
base-image: quay.io/fedora/fedora-kinoite
image-version: 44

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      cleanup: true
      nonfree: rpmfusion
      copr:
        - bieszczaders/kernel-cachyos # официальный и проверенный COPR с ядрами CachyOS для Fedora
        - lihaohong/yazi
      #  - atim/starship
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
        - https://packages.microsoft.com/yumrepos/vscode/config.repo

    # ОПЕРАЦИЯ ЗАМЕНЫ ЯДРА (Происходит атомарно во время сборки образа)
    replace:
      from-repo: copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos
      packages:
        - kernel
        - kernel-core
        - kernel-modules
        - kernel-modules-core
        - kernel-modules-extra
    install:
      packages:
        # Драйверы графики NVIDIA (akmods автоматически подхватит установленное ядро cachyos)
        #- akmod-nvidia-open
        #- xorg-x11-drv-nvidia-cuda
        #- nvidia-vaapi-driver
        #- xorg-x11-drv-nvidia-libs.i686 # 32-битные (i686) компоненты официального драйвера NVIDIA и технологии CUDA
        #- xorg-x11-drv-nvidia-cuda.i686 # 32-битные (i686) компоненты официального драйвера NVIDIA и технологии CUDA
        #- ark # нативный архиватор KDE (уже есть)
        - bat # вместо cat
        - brave-origin
        - btop
        - cachyos-settings  # Твики планировщиков и системных лимитов (sysctl) от команды CachyOS
        - cifs-utils # для монтирования Samba через /etc/fstab
        - cmatrix # заставка Матрица
        - code
        #- cosign # (уже есть)
        - cowsay # говорящая корова и другие ASCII картинки
        #- dolphin # нативный файловый менеджер KDE (уже есть)
        - fastfetch
        #- filelight # диаграмма распределения места на дисках (уже есть)
        - fortune # цитаты
        #- git # (уже есть)
        - goverlay # для настройки датчиков MangoHud
        - gwenview # нативный просмоторщик изображений KDE
        - haruna # нативный видеоплеер для KDE
        - hello
        #- hollywood # заставка Эмуляция бурной деятельности (rpm пакет не найден)
        - kate # улучшенный текстовый редактор KDE
        - kernel-cachyos # Так как мы подключили COPR выше, DNF сам возьмет эти пакеты оттуда
        - kernel-cachyos-devel # дополнительный сборочный пакет (headers), обязательный для компиляции драйверов NVIDIA
        - kcalc
        - keepassxc
        #- kio-extras # для открытия Samba в Dolphin (уже есть)
        #- kio-fuse # для открытия Samba в Dolphin (уже есть)
        - mangohud # MangoHud для rpm версий лаунчеров
        # Важнейшие 32-битные библиотеки Vulkan и Mesa для графики Intel/AMD (Mesa-drivers)
        # Они обязательны, чтобы игры запускались через Proton
        - mesa-vulkan-drivers.i686 # актуально для видеочипов Intel/AMD (возможно нужны и для NVIDIA)
        - mesa-dri-drivers.i686 # актуально для видеочипов Intel/AMD (возможно нужны и для NVIDIA)
        - mc
        #- micro
        #- nano # (уже есть)
        - okular # просмоторщик PDF
        - p7zip # для работы с 7zip архивами
        - p7zip-plugins # для работы с 7zip архивами
        - qbittorrent
        #- samba-client # набор CLI-утилит для Samba (уже есть)
        #- starship
        - steam
        - steam-devices # Крайне важный пакет: драйверы и правила для геймпадов (DualShock/DualSense/Xbox)
        - thunderbird
        - tldr # справка по командам Linux
        #- tree # для древовидного вывода папок (уже есть)
        - uksmd # Автоматическая дедупликация памяти от команды CachyOS
        - unrar # для распаковки RAR архивов
        #- unzip # (уже есть)
        #- vi # (уже есть)
        - vkBasalt.x86_64 # vkBasalt версия для современных 64-битных игр и программ (для rpm версий лаунчеров)
        - vkBasalt.i686 # vkBasalt версия для старых 32-битных игр (а также для многих классических игр в Steam, которые запускаются через Proton/Wine) (для rpm версий лаунчеров)
        - yazi # файловый менеджер на Rust
        #- zip # (уже есть)
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true # Send notification after install/uninstall is finished (true/false)
        repo:
          url: https://mirror.sjtu.edu.cn/flathub
          name: flathub
          title: Flathub (SJTUG Mirror)
        install: []
        # If no repo information is specified, Flathub will be used by default
        #install: # system flatpaks we want all users to have and not remove
          #- org.mozilla.firefox
          #- org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages
        notify: true # Send notification after install/uninstall is finished (true/false)
        repo:
          url: https://mirror.sjtu.edu.cn/flathub
          name: flathub
          title: Flathub (SJTUG Mirror)
        install:
          - com.ranfdev.DistroShelf # DistroShelf для управления Distrobox контейнерами
          - org.jeffvli.feishin # аудио плеер под стриминг
          - com.github.tchx84.Flatseal # Flatseal для управления разрешениями Flatpak
          - it.mijorus.gearlever # Gear Lever для управления AppImages
          - com.heroicgameslauncher.hgl # Heroic Games Launcher
          - org.jellyfin.JellyfinDesktop
          - io.github.DenysMb.Kontainer # Kontainer для управления Distrobox контейнерами
          - org.freedesktop.Platform.VulkanLayer.MangoHud # MangoHud для Flatpak версий лаунчеров
          - io.missioncenter.MissionCenter # монитор ресурсов
          - md.obsidian.Obsidian
          #- io.github.peazip.PeaZip # альтернативный архиватор (если Ark не устроит)
          - io.podman_desktop.PodmanDesktop
          - com.vysp3r.ProtonPlus # ProtonPlus
          - com.github.Matoking.protontricks # Protontricks
          - net.davidotek.pupgui2 # ProtonUp-Qt (альтернатива ProtonPlus)
          - org.telegram.desktop
          - org.freedesktop.Platform.VulkanLayer.vkBasalt # vkBasalt (для Flatpak версий лаунчеров) - аналог ReShade 
          - org.videolan.VLC
          - io.github.flattool.Warehouse # Warehouse для управления Flatpak пакетами

  - type: brew # Homebrew

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
